model_info:
    model_name: qwen-turbo
    api_key:
    base_url: https://dashscope.aliyuncs.com/compatible-mode/v1
    temperature: 0.9
memobase:
    project_url: YOUR_PROJECT_URL
    api_key: YOUR_API_KEY
